### ISSUE TITLE
External configuration

### ISSUE THREAD

**Issue by TimPietrusky** [NERDDISCO/luminave-thorium#2]
Right now it's not possible to change the IP or host of either Thorium or luminave-server from the outside without updating the code. This means that when Thorium is running production-mode, it will not work. Also we can't change the port of luminave-server. 

## ToDo

- [x]  **Thorium**: IP / port OR if the IP should be fetched automagically using bonjour
- [x] **luminave-server**: IP / port
- [x] Debug mode: Enable or disable log messages

**Comment by TimPietrusky** [comment]
Debug mode can be set, but when you set the NODE_ENV it will still not work, because webpack will overwrite it with it's `mode` option. This will be fixed in #3
